### ISSUE TITLE
where is the data?

### ISSUE THREAD

**Issue by xinzhou100** [jpgrana/bayesian-approach-predicting-well-production#1]

**Comment by mpagazehe** [comment]
Please provide us with the data. Thank you

**Comment by jpgrana** [comment]
Sorry, not available.  Data was provided by a company and proprietary.

**Comment by mpagazehe** [comment]
Thank you for the feedback. I appreciate. I will try using my own data and see how it goes. Again thank you so much

At2020-12-02 11:19:37，Jeff Grananotifications@github.comwrote:

Sorry, not available. Data was provided by a company and proprietary.

**Comment by mpagazehe** [comment]
Dear sir,
Is there anyway you could get me any data that I can use in running and testing this code. Thank you

At2020-12-02 11:19:40，Jeff Grananotifications@github.comwrote:

Closed #1.
